spring:
  application:
    name: employees
  datasource:
    url: jdbc:mysql://localhost:3306/employees
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: false


#docker run -p 3306:3306 --name employees \
#-e MYSQL_ROOT_PASSWORD=root \
#-e MYSQL_DATABASE=employees \
#-v /Users/rajprakash/projects/docker/volumes/employees:/var/lib/mysql -d mysql
